# This file is generated by packaging/homebrew/update.sh on each release.
# Do not edit by hand; changes will be overwritten.
class Nono < Formula
  desc "Kernel-enforced sandbox for AI agents, MCP servers and LLM workloads"
  homepage "https://github.com/vjeantet/nono"
  version "0.67.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/vjeantet/nono/releases/download/v0.67.2/nono-v0.67.2-aarch64-apple-darwin.tar.gz"
      sha256 "3b2872a83887bcc46878e81b0cb9c2865c9291988b0709fbf2fdfa0b0eb6ae3d"
    end
    on_intel do
      url "https://github.com/vjeantet/nono/releases/download/v0.67.2/nono-v0.67.2-x86_64-apple-darwin.tar.gz"
      sha256 "555dd853ebf558e87e1ebdac02a58027507ae2e824f311562576687b775aa559"
    end
  end

  def install
    bin.install "nono"
  end

  test do
    system "#{bin}/nono", "--version"
  end
end
