# This file is generated by packaging/homebrew/update.sh on each release.
# Do not edit by hand; changes will be overwritten.
class Nono < Formula
  desc "Kernel-enforced sandbox for AI agents, MCP servers and LLM workloads"
  homepage "https://github.com/vjeantet/nono"
  version "0.65.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/vjeantet/nono/releases/download/v0.65.3/nono-v0.65.3-aarch64-apple-darwin.tar.gz"
      sha256 "dfa33e677aac3f4b11d06988500409613afe1df984abd3d5d52521e2f2a60054"
    end
    on_intel do
      url "https://github.com/vjeantet/nono/releases/download/v0.65.3/nono-v0.65.3-x86_64-apple-darwin.tar.gz"
      sha256 "9670493f29f7b2d9a585f2673839e25db8776aa5ab7f81ffcce955a768084cb3"
    end
  end

  def install
    bin.install "nono"
  end

  test do
    system "#{bin}/nono", "--version"
  end
end
